/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import classes.usuarios;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import persistencia.conexao;

/**
 *
 * @author Igor
 */
public class Entrar extends javax.swing.JFrame {

    principal principal = new principal();

    String usuario = "", senha = "";
    int acao = 0;

    /**
     * Creates new form Entrar
     */
    public Entrar() {

        // entrar.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoUsu = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botaoEntrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        campoUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuActionPerformed(evt);
            }
        });
        campoUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoUsuKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoUsuKeyReleased(evt);
            }
        });

        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });
        campoSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoSenhaKeyPressed(evt);
            }
        });

        jLabel1.setText("Usuario:");

        jLabel2.setText("Senha:");

        botaoEntrar.setText("Entrar");
        botaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarActionPerformed(evt);
            }
        });
        botaoEntrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoEntrarKeyPressed(evt);
            }
        });

        jLabel3.setText("Diferencia se Maiuscula ou Minuscula!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(campoUsu)
                    .addComponent(campoSenha)
                    .addComponent(botaoEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(45, 45, 45)
                .addComponent(botaoEntrar)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuActionPerformed

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaActionPerformed

    private void botaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarActionPerformed
        usuario = campoUsu.getText();
        senha = campoSenha.getText();

        try {
            usuEntrar();
        } catch (SQLException ex) {
            Logger.getLogger(Entrar.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (acao == 1) {
            //principal principal = new principal();

            principal.setVisible(true);
            principal.setLocationRelativeTo(this);

        } else {
            JOptionPane.showMessageDialog(null, " Usuario ou senha é invalido!");
            campoUsu.requestFocus();
        }

        dispose(); //Fechar tela atal
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEntrarActionPerformed

    private void campoUsuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoUsuKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            campoSenha.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuKeyPressed

    private void campoSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoSenhaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            botaoEntrar.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaKeyPressed

    private void botaoEntrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoEntrarKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            botaoEntrar.doClick(); // metodo doClick é igual a clicar com o mouse no botao
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEntrarKeyPressed

    private void campoUsuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoUsuKeyReleased
        campoUsu.setText(campoUsu.getText().toUpperCase()); //deixar o teste em maiusculo
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuKeyReleased

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Entrar entrar = new Entrar();

                entrar.setVisible(true);
                entrar.setLocationRelativeTo(null);
            }
        });
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    public void usuEntrar() throws SQLException {

        conexao conexao = new conexao();
        conexao.getConexao();
        String selectSQL = "SELECT * FROM USUARIOS A WHERE A.usu_nome LIKE '" + usuario + "'";

        Statement pstmtCon;
        pstmtCon = conexao.getConexao().createStatement();

        ResultSet rs = pstmtCon.executeQuery(selectSQL);

        while (rs.next()) {
            String senhaBD = rs.getString("usu_senha");

            if (senha.equals(senhaBD)) {
                acao = 1;
            } else {
                acao = 2;
            }

            //permissoes
            if (acao == 1) {

                String usu_perUsuarios = rs.getString("usu_perUsuarios");
                String usu_perVendas = rs.getString("usu_perVendas");
                String usu_perProdutos = rs.getString("usu_perProdutos");
                String usu_perPessoas = rs.getString("usu_perPessoas");
                String usu_perEstoque = rs.getString("usu_perEstoque");
                String usu_perRltVendas = rs.getString("usu_perRltVendas");
                String usu_perEmpresa = rs.getString("usu_perEmpresa");
                String usu_perDespesas = rs.getString("usu_perQualquer2"); //mudar nome no SQL

                if (usu_perUsuarios.equals("S")) {
                    principal.botaoVendas.setEnabled(false);
                }
                if (usu_perVendas.equals("S")) {
                    principal.botaoVendas.setEnabled(false);
                    principal.getMenuBar().getMenu(0);
                    //principal.setMenuB
                }
                if (usu_perProdutos.equals("S")) {
                    principal.botaoProdutos.setEnabled(false);
                }
                if (usu_perPessoas.equals("S")) {
                    principal.botaoPessoas.setEnabled(false);
                    //  principal.
                }
                if (usu_perEstoque.equals("S")) {
                    principal.botaoVendas.setEnabled(false);
                }
                if (usu_perRltVendas.equals("S")) {
                    principal.botaoVendas.setEnabled(false);
                }
                if (usu_perEmpresa.equals("S")) {
                    principal.botaoVendas.setEnabled(false);
                }
                if (usu_perDespesas.equals("S")) {
                    principal.botaoVendas.setEnabled(false);
                }

            }
        }

    }

}
