/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import relatorios.*;

import classes.pessoas;

/**
 *
 * @author Igor
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        menuBar3 = new java.awt.MenuBar();
        menu5 = new java.awt.Menu();
        menu6 = new java.awt.Menu();
        botaoPessoas = new javax.swing.JButton();
        botaoVendas = new javax.swing.JButton();
        botaoProdutos = new javax.swing.JButton();
        menus = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        cadastroPessoas = new javax.swing.JMenuItem();
        cadastroProdutos = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        consultaVendas = new javax.swing.JMenuItem();
        consultaEstoque = new javax.swing.JMenuItem();
        menuVendas = new javax.swing.JMenu();
        vendasRealizarVendas = new javax.swing.JMenuItem();
        munuTeste = new javax.swing.JMenu();
        testeTeste = new javax.swing.JMenuItem();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        menu5.setLabel("File");
        menuBar3.add(menu5);

        menu6.setLabel("Edit");
        menuBar3.add(menu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicial");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        botaoPessoas.setText("Incluir / Pesquisar - Pessoas");
        botaoPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPessoasActionPerformed(evt);
            }
        });

        botaoVendas.setText("Vendas");
        botaoVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVendasActionPerformed(evt);
            }
        });

        botaoProdutos.setText("Incluir / Pesquisar - Produtos");
        botaoProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProdutosActionPerformed(evt);
            }
        });

        menuCadastro.setText("Cadastro");
        menuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroActionPerformed(evt);
            }
        });

        cadastroPessoas.setText("Cadastro de Pessoas");
        cadastroPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroPessoasActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroPessoas);

        cadastroProdutos.setText("Cadastro de Produtos");
        cadastroProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroProdutosActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroProdutos);

        menus.add(menuCadastro);

        menuConsultas.setText("Consulta");

        consultaVendas.setText("Consulta de Vendas");
        consultaVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaVendasActionPerformed(evt);
            }
        });
        menuConsultas.add(consultaVendas);

        consultaEstoque.setText("Consulta de Estoque");
        consultaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaEstoqueActionPerformed(evt);
            }
        });
        menuConsultas.add(consultaEstoque);

        menus.add(menuConsultas);

        menuVendas.setText("Vendas");

        vendasRealizarVendas.setText("Realizar Vendas");
        vendasRealizarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendasRealizarVendasActionPerformed(evt);
            }
        });
        menuVendas.add(vendasRealizarVendas);

        menus.add(menuVendas);

        munuTeste.setText("testes");
        munuTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                munuTesteActionPerformed(evt);
            }
        });

        testeTeste.setText("Testar");
        testeTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testeTesteActionPerformed(evt);
            }
        });
        munuTeste.add(testeTeste);

        menus.add(munuTeste);

        setJMenuBar(menus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(botaoPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(botaoProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(botaoVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(424, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastroActionPerformed

    private void cadastroPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroPessoasActionPerformed
        CadastroPessoas CadastroPessoas = new CadastroPessoas();
        
        CadastroPessoas.setVisible(true);
        CadastroPessoas.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroPessoasActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(this.MAXIMIZED_BOTH);

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void cadastroProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroProdutosActionPerformed
        CadastroProdutos CadastroProdutos = new CadastroProdutos();
        
        CadastroProdutos.setVisible(true);
        CadastroProdutos.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroProdutosActionPerformed

    private void botaoPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPessoasActionPerformed
        cadastroPessoasActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoPessoasActionPerformed

    private void botaoProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProdutosActionPerformed
        cadastroProdutosActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoProdutosActionPerformed

    private void vendasRealizarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendasRealizarVendasActionPerformed
        RealizarVendas RealizarVendas = new RealizarVendas();
        
        RealizarVendas.setVisible(true);
        RealizarVendas.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_vendasRealizarVendasActionPerformed

    private void botaoVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVendasActionPerformed
        vendasRealizarVendasActionPerformed(evt);

        // TODO add your handling code here:
    }//GEN-LAST:event_botaoVendasActionPerformed

    private void consultaVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaVendasActionPerformed
        relatorioVendas relatorioVendas = new relatorioVendas();
        
        relatorioVendas.setVisible(true);
        relatorioVendas.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaVendasActionPerformed

    private void consultaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaEstoqueActionPerformed
        estoque estoque = new estoque();
        
        estoque.setVisible(true);
        estoque.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaEstoqueActionPerformed

    private void munuTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_munuTesteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_munuTesteActionPerformed

    private void testeTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testeTesteActionPerformed
        testes teste = new testes();
        
        teste.setVisible(true);
        teste.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_testeTesteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botaoPessoas;
    public javax.swing.JButton botaoProdutos;
    public javax.swing.JButton botaoVendas;
    public javax.swing.JMenuItem cadastroPessoas;
    public javax.swing.JMenuItem cadastroProdutos;
    private javax.swing.JMenuItem consultaEstoque;
    private javax.swing.JMenuItem consultaVendas;
    public java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.Menu menu5;
    private java.awt.Menu menu6;
    public java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.MenuBar menuBar3;
    public javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuVendas;
    public javax.swing.JMenuBar menus;
    private javax.swing.JMenu munuTeste;
    private javax.swing.JMenuItem testeTeste;
    private javax.swing.JMenuItem vendasRealizarVendas;
    // End of variables declaration//GEN-END:variables

    private static class Inicial {
        
        public Inicial() {
            
        }
        
    }
    
}
